import "server-only";

import { createAdminClient } from "@/lib/supabase/server";
import type {
  CompraCreateInput,
  CompraListParams,
  CompraRow,
  CompraListResponse,
} from "@/lib/types/compra";

function buildQueryOptions(page: number, pageSize: number) {
  const safePage = Math.max(1, page);
  const safePageSize = Math.max(1, pageSize);
  const from = (safePage - 1) * safePageSize;
  const to = from + safePageSize - 1;
  return { safePage, safePageSize, from, to };
}

function applyDateFilters(
  query: ReturnType<typeof createAdminClient.prototype.from>,
  filters?: CompraListParams["filters"]
) {
  if (filters?.fechaDesde) {
    query = query.gte("fecha", filters.fechaDesde);
  }
  if (filters?.fechaHasta) {
    query = query.lte("fecha", filters.fechaHasta);
  }
  return query;
}

/**
 * Creates a new compra record. UUID is generated by the DB.
 */
export async function createCompra(
  input: CompraCreateInput
): Promise<CompraRow> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .insert({
      fecha: input.fecha,
      id_usuario: input.id_usuario,
      subtotal: input.subtotal,
      total: input.total,
      id_promocion: input.id_promocion ?? null,
    })
    .select("*")
    .single();

  if (error) {
    console.error("[compraModel] Error al crear compra:", error);
    throw error;
  }

  return data;
}

/**
 * Gets paginated compras for a user with optional date range filters.
 */
export async function getComprasByUserId(
  userId: string,
  params: CompraListParams
): Promise<CompraListResponse> {
  const adminClient = createAdminClient();

  const { page, pageSize, filters } = params;
  const { safePage, safePageSize, from, to } = buildQueryOptions(page, pageSize);

  let query = adminClient
    .from("compra")
    .select("*", { count: "exact" })
    .eq("id_usuario", userId)
    .order("fecha", { ascending: false })
    .range(from, to);

  query = applyDateFilters(query, filters);

  const { data, error, count } = await query;

  if (error) {
    console.error("[compraModel] Error al obtener compras por usuario:", error);
    throw error;
  }

  return {
    data: (data as CompraRow[]) ?? ([] as CompraRow[]),
    total: count || 0,
    page: safePage,
    pageSize: safePageSize,
    totalPages: Math.ceil((count || 0) / safePageSize),
  };
}

/**
 * Gets a single compra by its UUID.
 */
export async function getCompraById(
  id: string
): Promise<CompraRow | null> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) {
    console.error("[compraModel] Error al obtener compra por ID:", error);
    throw error;
  }

  return data;
}

/**
 * Checks if a compra exists by ID. Used for FK validation.
 */
export async function checkCompraExistsById(
  id: string
): Promise<boolean> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .select("id")
    .eq("id", id)
    .limit(1)
    .maybeSingle();

  if (error) {
    console.error("[compraModel] Error al verificar existencia de compra por ID:", error);
    throw error;
  }

  return !!data;
}
