import "server-only";

import { createAdminClient } from "@/lib/supabase/server";
import { MAX_PAGE_SIZE } from "@/lib/validations/rules";
import type {
  CompraCreateInput,
  CompraListParams,
  CompraRow,
  CompraConItems,
  CompraItem,
  CompraHistorialResponse,
} from "@/lib/types/compra";

function buildQueryOptions(page: number, pageSize: number) {
  const safePage = Math.max(1, page);
  const safePageSize = Math.min(Math.max(1, pageSize), MAX_PAGE_SIZE);
  const from = (safePage - 1) * safePageSize;
  const to = from + safePageSize - 1;
  return { safePage, safePageSize, from, to };
}

type DateFilterQuery<T> = {
  gte(column: string, value: string): T;
  lte(column: string, value: string): T;
};

function applyDateFilters<T extends DateFilterQuery<T>>(
  query: T,
  filters?: CompraListParams["filters"]
) {
  if (filters?.fechaDesde) {
    query = query.gte("fecha", filters.fechaDesde);
  }
  if (filters?.fechaHasta) {
    query = query.lte("fecha", filters.fechaHasta);
  }
  return query;
}

function extractCoverImage(
  noticias: { imagenes: unknown; deleted_at: string | null; es_visible: boolean }[] | undefined
): string | null {
  const activas = (noticias ?? []).filter((n) => !n.deleted_at && n.es_visible);
  const imagenes = activas[0]?.imagenes;
  if (!Array.isArray(imagenes) || imagenes.length === 0) return null;
  return typeof imagenes[0] === "string" ? imagenes[0] : null;
}

function groupItemsByLibro(
  rawItems: { copia?: { libro?: { id: string; titulo: string; precio: number; editorial: string; idioma: string; noticias?: { imagenes: unknown; deleted_at: string | null; es_visible: boolean }[] } } }[]
): CompraItem[] {
  const grouped = new Map<string, CompraItem>();

  for (const raw of rawItems) {
    const libro = raw.copia?.libro;
    if (!libro) continue;

    const existing = grouped.get(libro.id);
    if (existing) {
      existing.cantidad++;
    } else {
      grouped.set(libro.id, {
        libro: {
          id: libro.id,
          titulo: libro.titulo,
          precio: libro.precio,
          editorial: libro.editorial,
          idioma: libro.idioma,
        },
        cantidad: 1,
        imagen_portada: extractCoverImage(libro.noticias),
        precio_unitario: libro.precio,
      });
    }
  }

  return Array.from(grouped.values());
}

function transformCompras(
  data: { id: string; fecha: string; subtotal: number; total: number; id_promocion: number | null; items?: unknown[] }[] | null
): CompraConItems[] {
  return (data ?? []).map((compra) => ({
    id: compra.id,
    fecha: compra.fecha,
    subtotal: compra.subtotal,
    total: compra.total,
    id_promocion: compra.id_promocion,
    items: groupItemsByLibro(compra.items as { copia?: { libro?: { id: string; titulo: string; precio: number; editorial: string; idioma: string; noticias?: { imagenes: unknown; deleted_at: string | null; es_visible: boolean }[] } } }[]),
  }));
}

/**
 * Creates a new compra record. UUID is generated by the DB.
 */
export async function createCompra(
  input: CompraCreateInput
): Promise<CompraRow> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .insert({
      fecha: input.fecha,
      id_usuario: input.id_usuario,
      subtotal: input.subtotal,
      total: input.total,
      id_promocion: input.id_promocion ?? null,
    })
    .select("*")
    .single();

  if (error) {
    console.error("[compraModel] Error al crear compra:", error);
    throw error;
  }

  return data;
}

/**
 * Gets paginated compras for a user with items, books and cover images.
 */
export async function getComprasByUserId(
  userId: string,
  params: CompraListParams
): Promise<CompraHistorialResponse> {
  const adminClient = createAdminClient();
  const { page, pageSize, filters } = params;
  const { safePage, safePageSize, from, to } = buildQueryOptions(page, pageSize);

  let query = adminClient
    .from("compra")
    .select(
      `
      *,
      items:item_compra(
        id,
        id_copia,
        copia(
          id_libro,
          libro(
            id,
            titulo,
            precio,
            editorial,
            idioma,
            noticias(
              imagenes,
              deleted_at,
              es_visible
            )
          )
        )
      )
    `,
      { count: "exact" }
    )
    .eq("id_usuario", userId)
    .order("fecha", { ascending: false })
    .range(from, to);

  query = applyDateFilters(query, filters);

  const { data, error, count } = await query;

  if (error) {
    console.error("[compraModel] Error al obtener historial de compras:", error);
    throw error;
  }

  return {
    data: transformCompras(data),
    total: count || 0,
    page: safePage,
    pageSize: safePageSize,
    totalPages: Math.ceil((count || 0) / safePageSize),
  };
}

/**
 * Gets a single compra by its UUID.
 */
export async function getCompraById(
  id: string
): Promise<CompraRow | null> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) {
    console.error("[compraModel] Error al obtener compra por ID:", error);
    throw error;
  }

  return data;
}

/**
 * Checks if a compra exists by ID. Used for FK validation.
 */
export async function checkCompraExistsById(
  id: string
): Promise<boolean> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .select("id")
    .eq("id", id)
    .limit(1)
    .maybeSingle();

  if (error) {
    console.error("[compraModel] Error al verificar existencia de compra por ID:", error);
    throw error;
  }

  return !!data;
}
