import "server-only";

import { createAdminClient } from "@/lib/supabase/server";
import { MAX_PAGE_SIZE } from "@/lib/validations/rules";
import type {
  CompraCreateInput,
  CompraListParams,
  CompraRow,
  CompraConItems,
  CompraItem,
  CompraHistorialResponse,
  CompraDetalleExtra,
  CompraTarjetaInfo,
  CompraEntregaInfo,
} from "@/lib/types/compra";

function buildQueryOptions(page: number, pageSize: number) {
  const safePage = Math.max(1, page);
  const safePageSize = Math.min(Math.max(1, pageSize), MAX_PAGE_SIZE);
  const from = (safePage - 1) * safePageSize;
  const to = from + safePageSize - 1;
  return { safePage, safePageSize, from, to };
}

type DateFilterQuery<T> = {
  gte(column: string, value: string): T;
  lte(column: string, value: string): T;
};

function applyDateFilters<T extends DateFilterQuery<T>>(
  query: T,
  filters?: CompraListParams["filters"]
) {
  if (filters?.fechaDesde) {
    query = query.gte("fecha", filters.fechaDesde);
  }
  if (filters?.fechaHasta) {
    query = query.lte("fecha", filters.fechaHasta);
  }
  return query;
}

function extractCoverImage(
  noticias: { imagenes: unknown; deleted_at: string | null; es_visible: boolean }[] | undefined
): string | null {
  const activas = (noticias ?? []).filter((n) => !n.deleted_at && n.es_visible);
  const imagenes = activas[0]?.imagenes;
  if (!Array.isArray(imagenes) || imagenes.length === 0) return null;
  return typeof imagenes[0] === "string" ? imagenes[0] : null;
}

function groupItemsByLibro(
  rawItems: { monto: number; copia?: { libro?: { id: string; titulo: string; precio: number; editorial: string; idioma: string; noticias?: { imagenes: unknown; deleted_at: string | null; es_visible: boolean }[] } } }[]
): CompraItem[] {
  const grouped = new Map<string, CompraItem>();

  for (const raw of rawItems) {
    const libro = raw.copia?.libro;
    if (!libro) continue;

    const key = `${libro.id}__${raw.monto}`;
    const existing = grouped.get(key);
    if (existing) {
      existing.cantidad++;
    } else {
      grouped.set(key, {
        libro: {
          id: libro.id,
          titulo: libro.titulo,
          precio: libro.precio,
          editorial: libro.editorial,
          idioma: libro.idioma,
        },
        cantidad: 1,
        imagen_portada: extractCoverImage(libro.noticias),
        precio_unitario: raw.monto,
      });
    }
  }

  return Array.from(grouped.values());
}

function transformCompras(
  data: { id: string; fecha: string; subtotal: number; total: number; id_promocion: number | null; items?: unknown[] }[] | null
): CompraConItems[] {
  return (data ?? []).map((compra) => ({
    id: compra.id,
    fecha: compra.fecha,
    subtotal: compra.subtotal,
    total: compra.total,
    id_promocion: compra.id_promocion,
    items: groupItemsByLibro(compra.items as { monto: number; copia?: { libro?: { id: string; titulo: string; precio: number; editorial: string; idioma: string; noticias?: { imagenes: unknown; deleted_at: string | null; es_visible: boolean }[] } } }[]),
  }));
}

/**
 * Creates a new compra record. UUID is generated by the DB.
 */
export async function createCompra(
  input: CompraCreateInput
): Promise<CompraRow> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .insert({
      fecha: input.fecha,
      id_usuario: input.id_usuario,
      subtotal: input.subtotal,
      total: input.total,
      id_promocion: input.id_promocion ?? null,
    })
    .select("*")
    .single();

  if (error) {
    console.error("[compraModel] Error al crear compra:", error);
    throw error;
  }

  return data;
}

/**
 * Gets paginated compras for a user with items, books and cover images.
 */
export async function getComprasByUserId(
  userId: string,
  params: CompraListParams
): Promise<CompraHistorialResponse> {
  const adminClient = createAdminClient();
  const { page, pageSize, filters } = params;
  const { safePage, safePageSize, from, to } = buildQueryOptions(page, pageSize);

  let query = adminClient
    .from("compra")
    .select(
      `
      *,
      items:item_compra(
        id,
        id_copia,
        monto,
        copia(
          id_libro,
          libro(
            id,
            titulo,
            precio,
            editorial,
            idioma,
            noticias(
              imagenes,
              deleted_at,
              es_visible
            )
          )
        )
      )
    `,
      { count: "exact" }
    )
    .eq("id_usuario", userId)
    .order("fecha", { ascending: false })
    .range(from, to);

  query = applyDateFilters(query, filters);

  const { data, error, count } = await query;

  if (error) {
    console.error("[compraModel] Error al obtener historial de compras:", error);
    throw error;
  }

  return {
    data: transformCompras(data),
    total: count || 0,
    page: safePage,
    pageSize: safePageSize,
    totalPages: Math.ceil((count || 0) / safePageSize),
  };
}

/**
 * Gets a single compra by its UUID.
 */
export async function getCompraById(
  id: string
): Promise<CompraRow | null> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) {
    console.error("[compraModel] Error al obtener compra por ID:", error);
    throw error;
  }

  return data;
}

/**
 * Gets a single compra with its items enriched (book info + cover images).
 * Returns null if not found.
 */
export async function getCompraDetalleById(
  id: string
): Promise<CompraConItems | null> {
  const adminClient = createAdminClient();

  const { data, error } = await adminClient
    .from("compra")
    .select(
      `
      *,
      items:item_compra(
        id,
        id_copia,
        monto,
        copia(
          id_libro,
          libro(
            id,
            titulo,
            precio,
            editorial,
            idioma,
            noticias(
              imagenes,
              deleted_at,
              es_visible
            )
          )
        )
      )
    `
    )
    .eq("id", id)
    .maybeSingle();

  if (error) {
    console.error("[compraModel] Error al obtener detalle de compra:", error);
    throw error;
  }

  if (!data) return null;

  const [compra] = transformCompras([data]);
  return compra ?? null;
}

type RawTarjetaCompraRow = {
  monto: number;
  tarjeta: { ultimos_cuatro_digitos: string; nombre_titular: string | null } | null;
};

type RawEntregaRow = {
  tipo: string;
  estado: string;
  costo: number;
  fecha_entrega_estimada: string;
  fecha_entregado: string | null;
  direccion: { direccion_formateada: string } | null;
};

function mapTarjetas(data: RawTarjetaCompraRow[]): CompraTarjetaInfo[] {
  return data.map((t) => ({
    monto: t.monto,
    ultimos_cuatro_digitos: t.tarjeta?.ultimos_cuatro_digitos ?? "****",
    nombre_titular: t.tarjeta?.nombre_titular ?? null,
  }));
}

function mapEntrega(raw: RawEntregaRow): CompraEntregaInfo {
  return {
    tipo: raw.tipo,
    estado: raw.estado,
    costo: raw.costo,
    fecha_entrega_estimada: raw.fecha_entrega_estimada,
    fecha_entregado: raw.fecha_entregado,
    direccion: raw.direccion?.direccion_formateada ?? "Sin dirección",
  };
}

/**
 * Gets extra detail for a compra: payment cards and delivery info.
 * Returns null if the compra has no associated records or is not found.
 */
export async function getCompraDetalleExtraById(
  id: string
): Promise<CompraDetalleExtra> {
  const adminClient = createAdminClient();

  const [tarjetasResult, entregaResult] = await Promise.all([
    adminClient
      .from("tarjeta_compra")
      .select("monto, tarjeta(ultimos_cuatro_digitos, nombre_titular)")
      .eq("id_compra", id),
    adminClient
      .from("entrega")
      .select("tipo, estado, costo, fecha_entrega_estimada, fecha_entregado, direccion:direccion(direccion_formateada)")
      .eq("id_compra", id)
      .maybeSingle(),
  ]);

  if (tarjetasResult.error) {
    console.error("[compraModel] Error al obtener tarjetas de compra:", tarjetasResult.error);
    throw tarjetasResult.error;
  }

  if (entregaResult.error) {
    console.error("[compraModel] Error al obtener entrega de compra:", entregaResult.error);
    throw entregaResult.error;
  }

  const tarjetas = mapTarjetas((tarjetasResult.data ?? []) as RawTarjetaCompraRow[]);
  const entrega = entregaResult.data ? mapEntrega(entregaResult.data as unknown as RawEntregaRow) : null;

  return { tarjetas, entrega };
}
